# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sass Conf 2015

description: > # this means to ignore newlines until "baseurl:"
  Notes from Sass Conf 2015

baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude: ["node_modules", "gulp", "gulpfile.js", "package.json"]

permalink: /:title/
